### ISSUE TITLE
Retweet and Quote Tweets

### ISSUE THREAD

**Issue by Siamakka** [dmstern/likers-blocker#67] opened 2021-12-28 15:52 UTC
Thank you very much for this extension.
The only problem is that when it wants to block retweets, it also puts tweet quotes in the block list. If these two things are separated, it will be extraordinary.

**Comment by Sacred-Shadow** [comment] 2021-12-31 22:17
Only the retweet are blocked, i.e. if you share your opinion. 
A retweet as a quote, via which one may also critically deal with it there, is not blocked.

**Comment by dmstern** [comment] 2022-01-10 22:12
I'm not sure if I understand your request right. The second thing you describe ("A retweet as a quote [...] is not blocked.") is actually an intended feature we can not change, because only retweets (not quotes) are meant to reproduce the opinion of the original author and only these real retweets are being fetched via the Twitter API.

The first thing you wrote ("when it wants to block retweets, it also puts tweet quotes in the block list") is basically the opposite. Correct me if I'm totally wrong here, but as I understand it, your second statement is true (as intended), while the first ist not (or I misunderstood you ;)).

**Comment by dmstern** [comment] 2022-01-10 22:19
Quotet tweets are not being blocked, only *retweets* without additional text.
Since we do not plan to also block quoted tweets, I'll close this.

**Closed by dmstern** 2022-01-10 22:19 UTC
